apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gau-account-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: gau-account-secret
    creationPolicy: Owner
  data:
    - secretKey: PGPOOL_USER
      remoteRef:
        key: gau-account/staging
        property: PGPOOL_USER

    - secretKey: PGPOOL_PASSWORD
      remoteRef:
        key: gau-account/staging
        property: PGPOOL_PASSWORD

    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: gau-account/staging
        property: JWT_SECRET_KEY

    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: gau-account/staging
        property: REDIS_PASSWORD

    - secretKey: RABBITMQ_USER
      remoteRef:
        key: gau-account/staging
        property: RABBITMQ_USER

    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: gau-account/staging
        property: RABBITMQ_PASSWORD
