apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bao-staging-env

resources:
  - ../../base
  - namespace.yaml
  - externalsecret.yaml
  - configmap.yaml

patchesStrategicMerge:
  - ingress-patch.yaml
